### ISSUE TITLE
During build, GPG error - NO_PUBKEY 93C4A3FD7BB9C367

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-debian-9#1]
```
    virtualbox-iso: Err:4 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease
    virtualbox-iso: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367
    virtualbox-iso: Reading package lists...
    virtualbox-iso: W: GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367
    virtualbox-iso: E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease' is not signed.
```

Not sure if that actually harms anything though. I'm building a base box right now to test.

**Comment by cppcms-testing** [comment]
There is still no available key 93C4A3FD7BB9C367 as mentioned in the ansible documentation:
http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-debian
Can you please provide the right key if it has been revocated or it there is a key that exists? Thank you in advance.

**Comment by joseguzman1337** [comment]
Use this for install <  Tower 3.2.3  >
 --------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

Ansible 2.4.2.0 

`echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu zesty main' | \
     sudo tee /etc/apt/sources.list.d/ansible.list`

`curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367" | sudo apt-key add`

`sudo su -c 'apt-get update && apt-get install -y ansible=2.4.2.0-1ppa~zesty && apt-mark hold ansible'`

`apt install python-pip && apt install python3-pip && apt install ansible -y --allow-change-held-packages`

`apt autoremove -y`

`ansible --version`

**Comment by thorian93** [comment]
Just a ping as the key is **still not** available as described in the documentation!

I can access the key through the key identifier `0x93C4A3FD7BB9C367` as mentioned by @4k4xs4pH1r3 though, so a leading `0x` basically solved my problem.
