### ISSUE TITLE
Installation of VMware tools stop because the ifconfig is not available

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/packer-debian-9#3]
Standard installation of Debian 9 - based on preseed.cfg - doesn't contain the ifconfig command what cause that VMware Tools doesn't install correctly in non-interactive mode.

Installation stop with a question (checked under manual/interactive installation):
```
Setup is unable to find the "ifconfig" program on your machine. Please make sure it is installed. Do you want to specify the location of this program by hand? [yes]
```

The ifconfig command is included in the net-tools package.

**Comment by uguazelli** [comment]
maybe ifconfig is not installed.
to salved that 
sudo apt-get install net-tools

Than run the vmtools command again
