### ISSUE TITLE
how precess.cfg file  is created

### ISSUE THREAD

**Issue by junsionzhang** [geerlingguy/packer-debian-9#9]
hello,  thank you for all your perfect script. I have two questions about debian script:
1)how to get the boot_command list ?
2)how to generate the precess.cfg
what is command  to  select timezone and  apt source 
is this the reference https://www.debian.org/releases/stable/example-preseed.txt?

**Comment by geerlingguy** [comment]
This repository is being archived, all future work is moving to: https://github.com/geerlingguy/packer-boxes/issues/45
